DROP TABLE if EXISTS person;
CREATE TABLE IF NOT EXISTS person(
  id SERIAL PRIMARY KEY,
  email VARCHAR(50) NOT NULL,
  password VARCHAR(16) NOT NULL
);

DROP TABLE if EXISTS list;
CREATE TABLE IF NOT EXISTS list(
  id SERIAL PRIMARY KEY,
  user_id INTEGER REFERENCES person(id),
  table_name VARCHAR(24) NOT NULL
);

DROP TABLE if EXISTS list_item;
CREATE TABLE IF NOT EXISTS list_item(
  id SERIAL PRIMARY KEY,
  table_id INTEGER REFERENCES list(id),
  item_title VARCHAR(24) NOT NULL,
  item_description TEXT NOT NULL,
  is_completed BOOLEAN DEFAULT FALSE
);
