DROP TABLE if EXISTS todos;
CREATE TABLE IF NOT EXISTS todos(
  id SERIAL PRIMARY KEY,
  name VARCHAR(24) NOT NULL,
  description TEXT NOT NULL UNIQUE
);

DROP TABLE if EXISTS todoComplete;
CREATE TABLE IF NOT EXISTS todoComplete(
    todoID INTEGER REFERENCES todos(id),
    completedID INTEGER REFERENCES completed(id)
)

DROP TABLE if EXISTS completed;
CREATE TABLE IF NOT EXISTS completed(
  id SERIAL PRIMARY KEY,
  name VARCHAR(24) NOT NULL,
  description TEXT NOT NULL UNIQUE
)
